// Diamond inventory and jewelry data
export const diamondShapes = [
  "Round",
  "Princess",
  "Cushion",
  "Emerald",
  "Oval",
  "Radiant",
  "Asscher",
  "Marquise",
  "Heart",
  "Pear",
]

export const diamondClarity = ["FL", "IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "I1", "I2", "I3"]

export const diamondColor = ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N"]

export const diamondCut = ["Excellent", "Very Good", "Good", "Fair", "Poor"]

export const mockDiamonds = [
  {
    id: "diamond_1",
    shape: "Round",
    carat: 1.25,
    color: "G",
    clarity: "VS1",
    cut: "Excellent",
    price: 8500,
    certificateNumber: "GIA-2141234567",
    videoUrl: "/placeholder.svg?height=300&width=300",
    imageUrl: "/placeholder.svg?height=300&width=300",
    measurements: "6.85 x 6.88 x 4.25 mm",
    depth: 62.1,
    table: 57,
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    type: "Natural",
  },
  {
    id: "diamond_2",
    shape: "Princess",
    carat: 1.0,
    color: "F",
    clarity: "VVS2",
    cut: "Excellent",
    price: 6800,
    certificateNumber: "GIA-2141234568",
    videoUrl: "/placeholder.svg?height=300&width=300",
    imageUrl: "/placeholder.svg?height=300&width=300",
    measurements: "5.45 x 5.42 x 3.98 mm",
    depth: 73.2,
    table: 68,
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    type: "Lab Grown",
  },
  {
    id: "diamond_3",
    shape: "Cushion",
    carat: 1.5,
    color: "H",
    clarity: "SI1",
    cut: "Very Good",
    price: 7200,
    certificateNumber: "GIA-2141234569",
    videoUrl: "/placeholder.svg?height=300&width=300",
    imageUrl: "/placeholder.svg?height=300&width=300",
    measurements: "6.95 x 6.88 x 4.45 mm",
    depth: 64.5,
    table: 61,
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "None",
    type: "Natural",
  },
]

export const mockJewelryProducts = [
  {
    id: "jewelry_1",
    title: "Classic Solitaire Engagement Ring",
    handle: "classic-solitaire-engagement-ring",
    description: "Timeless solitaire setting perfect for showcasing your chosen diamond",
    basePrice: 1200,
    metal: "14K White Gold",
    setting: "Solitaire",
    images: ["/placeholder.svg?height=400&width=400"],
    compatibleShapes: ["Round", "Princess", "Cushion", "Oval"],
    ringSize: "6",
    category: "Engagement Rings",
  },
  {
    id: "jewelry_2",
    title: "Vintage Halo Engagement Ring",
    handle: "vintage-halo-engagement-ring",
    description: "Elegant vintage-inspired halo setting with intricate details",
    basePrice: 1800,
    metal: "18K Rose Gold",
    setting: "Halo",
    images: ["/placeholder.svg?height=400&width=400"],
    compatibleShapes: ["Round", "Cushion", "Oval", "Pear"],
    ringSize: "6.5",
    category: "Engagement Rings",
  },
  {
    id: "jewelry_3",
    title: "Three Stone Anniversary Ring",
    handle: "three-stone-anniversary-ring",
    description: "Symbolic three stone setting representing past, present, and future",
    basePrice: 2200,
    metal: "Platinum",
    setting: "Three Stone",
    images: ["/placeholder.svg?height=400&width=400"],
    compatibleShapes: ["Round", "Princess", "Emerald", "Asscher"],
    ringSize: "7",
    category: "Anniversary Rings",
  },
]

export const mockCurations = [
  {
    id: "curation_1",
    jewelryId: "jewelry_1",
    recommendedDiamonds: ["diamond_1", "diamond_2"],
    reason: "Perfect size and quality match for classic solitaire setting",
    confidence: 95,
    priceRange: { min: 6800, max: 8500 },
    totalPrice: 9700,
  },
  {
    id: "curation_2",
    jewelryId: "jewelry_2",
    recommendedDiamonds: ["diamond_3"],
    reason: "Cushion cut complements vintage halo design beautifully",
    confidence: 88,
    priceRange: { min: 7200, max: 7200 },
    totalPrice: 9000,
  },
]

export const mockAnalytics = {
  totalDiamonds: 15420,
  totalJewelry: 245,
  avgConversionRate: "12.5%",
  avgOrderValue: "$8,750",
  topPerformingShapes: [
    { shape: "Round", percentage: 45 },
    { shape: "Princess", percentage: 18 },
    { shape: "Cushion", percentage: 15 },
    { shape: "Oval", percentage: 12 },
    { shape: "Other", percentage: 10 },
  ],
  monthlyStats: [
    { month: "Jan", sales: 125000, orders: 18 },
    { month: "Feb", sales: 145000, orders: 22 },
    { month: "Mar", sales: 165000, orders: 25 },
    { month: "Apr", sales: 185000, orders: 28 },
    { month: "May", sales: 195000, orders: 31 },
    { month: "Jun", sales: 220000, orders: 35 },
  ],
}
