// Mock data for development and testing
export const mockProducts = [
  {
    id: "gid://shopify/Product/1",
    title: "Wireless Bluetooth Headphones",
    handle: "wireless-bluetooth-headphones",
    status: "ACTIVE",
    vendor: "TechCorp",
    productType: "Electronics",
    tags: ["wireless", "bluetooth", "audio"],
    description: "High-quality wireless Bluetooth headphones with noise cancellation.",
    images: [
      {
        id: "gid://shopify/ProductImage/1",
        url: "/placeholder.svg?height=300&width=300",
        altText: "Wireless Bluetooth Headphones",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/1",
        title: "Black",
        price: "99.99",
        compareAtPrice: "129.99",
        sku: "WBH-001-BLK",
        inventoryQuantity: 50,
        weight: 0.5,
        weightUnit: "KILOGRAMS",
      },
      {
        id: "gid://shopify/ProductVariant/2",
        title: "White",
        price: "99.99",
        compareAtPrice: "129.99",
        sku: "WBH-001-WHT",
        inventoryQuantity: 30,
        weight: 0.5,
        weightUnit: "KILOGRAMS",
      },
    ],
  },
  {
    id: "gid://shopify/Product/2",
    title: "Organic Cotton T-Shirt",
    handle: "organic-cotton-t-shirt",
    status: "ACTIVE",
    vendor: "EcoWear",
    productType: "Apparel",
    tags: ["organic", "cotton", "sustainable"],
    description: "Comfortable organic cotton t-shirt made from sustainable materials.",
    images: [
      {
        id: "gid://shopify/ProductImage/2",
        url: "/placeholder.svg?height=300&width=300",
        altText: "Organic Cotton T-Shirt",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/3",
        title: "Small / Blue",
        price: "29.99",
        compareAtPrice: null,
        sku: "OCT-001-S-BLU",
        inventoryQuantity: 25,
        weight: 0.2,
        weightUnit: "KILOGRAMS",
      },
      {
        id: "gid://shopify/ProductVariant/4",
        title: "Medium / Blue",
        price: "29.99",
        compareAtPrice: null,
        sku: "OCT-001-M-BLU",
        inventoryQuantity: 40,
        weight: 0.2,
        weightUnit: "KILOGRAMS",
      },
      {
        id: "gid://shopify/ProductVariant/5",
        title: "Large / Blue",
        price: "29.99",
        compareAtPrice: null,
        sku: "OCT-001-L-BLU",
        inventoryQuantity: 35,
        weight: 0.2,
        weightUnit: "KILOGRAMS",
      },
    ],
  },
  {
    id: "gid://shopify/Product/3",
    title: "Stainless Steel Water Bottle",
    handle: "stainless-steel-water-bottle",
    status: "ACTIVE",
    vendor: "HydroLife",
    productType: "Accessories",
    tags: ["water bottle", "stainless steel", "eco-friendly"],
    description: "Durable stainless steel water bottle that keeps drinks cold for 24 hours.",
    images: [
      {
        id: "gid://shopify/ProductImage/3",
        url: "/placeholder.svg?height=300&width=300",
        altText: "Stainless Steel Water Bottle",
      },
    ],
    variants: [
      {
        id: "gid://shopify/ProductVariant/6",
        title: "500ml / Silver",
        price: "24.99",
        compareAtPrice: "34.99",
        sku: "SSWB-500-SIL",
        inventoryQuantity: 60,
        weight: 0.3,
        weightUnit: "KILOGRAMS",
      },
      {
        id: "gid://shopify/ProductVariant/7",
        title: "750ml / Silver",
        price: "29.99",
        compareAtPrice: "39.99",
        sku: "SSWB-750-SIL",
        inventoryQuantity: 45,
        weight: 0.4,
        weightUnit: "KILOGRAMS",
      },
    ],
  },
]

export const mockOrders = [
  {
    id: "gid://shopify/Order/1001",
    name: "#1001",
    email: "customer@example.com",
    createdAt: "2024-01-15T10:30:00Z",
    totalPrice: "129.98",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customer: {
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/1",
        title: "Wireless Bluetooth Headphones",
        quantity: 1,
        price: "99.99",
      },
      {
        id: "gid://shopify/LineItem/2",
        title: "Organic Cotton T-Shirt",
        quantity: 1,
        price: "29.99",
      },
    ],
  },
  {
    id: "gid://shopify/Order/1002",
    name: "#1002",
    email: "customer2@example.com",
    createdAt: "2024-01-16T14:20:00Z",
    totalPrice: "54.98",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customer: {
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/3",
        title: "Stainless Steel Water Bottle",
        quantity: 2,
        price: "24.99",
      },
    ],
  },
]

export const mockCustomers = [
  {
    id: "gid://shopify/Customer/1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    createdAt: "2023-12-01T00:00:00Z",
    ordersCount: 3,
    totalSpent: "299.97",
    tags: ["VIP", "Repeat Customer"],
    addresses: [
      {
        address1: "123 Main St",
        city: "New York",
        province: "NY",
        country: "United States",
        zip: "10001",
      },
    ],
  },
  {
    id: "gid://shopify/Customer/2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "+1987654321",
    createdAt: "2024-01-10T00:00:00Z",
    ordersCount: 1,
    totalSpent: "54.98",
    tags: ["New Customer"],
    addresses: [
      {
        address1: "456 Oak Ave",
        city: "Los Angeles",
        province: "CA",
        country: "United States",
        zip: "90210",
      },
    ],
  },
]

export const mockAnalytics = {
  totalSales: "2,450.67",
  totalOrders: 45,
  averageOrderValue: "54.46",
  conversionRate: "2.3%",
  topProducts: [
    { name: "Wireless Bluetooth Headphones", sales: 15, revenue: "1,499.85" },
    { name: "Organic Cotton T-Shirt", sales: 23, revenue: "689.77" },
    { name: "Stainless Steel Water Bottle", sales: 12, revenue: "299.88" },
  ],
  salesByMonth: [
    { month: "Jan", sales: 1200 },
    { month: "Feb", sales: 1450 },
    { month: "Mar", sales: 1800 },
    { month: "Apr", sales: 2100 },
    { month: "May", sales: 1950 },
    { month: "Jun", sales: 2450 },
  ],
}
